name: audio_player_base
description: "A package for common audio player usage. Integrate with (just_audio)"
version: 0.0.1
homepage: ''
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio:
    path: ../../just_audio/just_audio
  just_audio_background:
    path: ../../just_audio/just_audio_background
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  rxdart: ^0.28.0
  hydrated_bloc: ^10.0.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  audio_video_progress_bar: ^2.0.3
  get_it: ^8.0.3
  path_provider: ^2.1.5
  http: ^1.4.0
  flutter_just_marquee: ^1.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: any
  json_serializable: ^6.9.5

flutter:
