name: audio_player_base
description: "A package for common audio player usage. Integrate with (just_audio)"
version: 0.0.1
homepage: ''

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  just_audio:
    path: ../../just_audio/just_audio
  just_audio_background:
    path: ../../just_audio/just_audio_background
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.4
  equatable: ^2.0.7

  rxdart: ^0.28.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: any
  json_serializable: ^6.8.0
  freezed: ^2.5.7

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
